theme: jekyll-theme-architect

name: Programmation Avancée 

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: Programmation Avancée et Patron de conception en Java

google_analytics: UA-29708002-2

plugins:
  - jekyll-sitemap

